# Generated by Django 5.1 on 2024-08-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("label", "0001_initial"),
        ("notes", "0003_collaborator_note_collaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="label",
            field=models.ManyToManyField(related_name="labels", to="label.label"),
        ),
    ]
