# Generated by Django 5.1 on 2024-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_note_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("url", models.TextField()),
                ("count", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "Log",
            },
        ),
    ]
